# -*- coding: utf-8 -*-
"""exp7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i_By0A1IVrYRs2GddPrzZCQk0OG_ayPB
"""

# ============================================================
# CUSTOMER SEGMENTATION USING K-MEANS CLUSTERING
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler


# ============================================================
# 1. CREATE DATASET
# ============================================================

data = {
    "CustomerID": range(1, 21),

    "Age": [
        19, 21, 22, 25, 28,
        31, 35, 40, 42, 45,
        48, 50, 52, 55, 58,
        60, 62, 65, 67, 70
    ],

    "Annual_Income": [
        15000, 18000, 20000, 22000, 25000,
        30000, 35000, 40000, 45000, 50000,
        55000, 60000, 65000, 70000, 75000,
        80000, 85000, 90000, 95000, 100000
    ],

    "Spending_Score": [
        85, 90, 88, 80, 82,
        75, 70, 65, 60, 55,
        50, 45, 40, 35, 30,
        25, 20, 18, 15, 10
    ]
}

df = pd.DataFrame(data)


# ============================================================
# 2. DISPLAY DATASET
# ============================================================

print("========== CUSTOMER DATASET ==========")
print(df)

print("\nDataset Shape:")
print(df.shape)


# ============================================================
# 3. SELECT FEATURES
# ============================================================

X = df[
    [
        "Annual_Income",
        "Spending_Score"
    ]
]


# ============================================================
# 4. STANDARDIZE THE DATA
# ============================================================

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)


# ============================================================
# 5. APPLY K-MEANS CLUSTERING
# ============================================================

kmeans = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

df["Cluster"] = kmeans.fit_predict(X_scaled)


# ============================================================
# 6. DISPLAY CLUSTERED DATA
# ============================================================

print("\n========== CUSTOMER SEGMENTS ==========")

print(
    df[
        [
            "CustomerID",
            "Age",
            "Annual_Income",
            "Spending_Score",
            "Cluster"
        ]
    ]
)


# ============================================================
# 7. DISPLAY CLUSTER CENTERS
# ============================================================

centers_scaled = kmeans.cluster_centers_

centers = scaler.inverse_transform(centers_scaled)

centers_df = pd.DataFrame(
    centers,
    columns=[
        "Annual_Income",
        "Spending_Score"
    ]
)

print("\n========== CLUSTER CENTERS ==========")
print(centers_df)


# ============================================================
# 8. VISUALIZE CUSTOMER SEGMENTS
# ============================================================

plt.figure(figsize=(8, 6))

plt.scatter(
    df["Annual_Income"],
    df["Spending_Score"],
    c=df["Cluster"],
    s=100
)

plt.scatter(
    centers[:, 0],
    centers[:, 1],
    marker="X",
    s=200
)

plt.xlabel("Annual Income")
plt.ylabel("Spending Score")

plt.title("Customer Segmentation Using K-Means")

plt.show()


# ============================================================
# 9. COUNT CUSTOMERS IN EACH CLUSTER
# ============================================================

print("\n========== CUSTOMERS PER CLUSTER ==========")

print(
    df["Cluster"]
    .value_counts()
    .sort_index()
)


# ============================================================
# 10. CLUSTER SUMMARY
# ============================================================

summary = df.groupby("Cluster")[
    [
        "Age",
        "Annual_Income",
        "Spending_Score"
    ]
].mean()

print("\n========== CLUSTER SUMMARY ==========")

print(summary)